version: '3'
services:
  server: 
    image: cat6-server 
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped

  app:
    image: cat6-app
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
     - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "8081:80"